# secret-sealed.yaml (Local)
# Pre-encrypted SealedSecret for local development.
# Decrypted in-cluster using the pre-imported key 'local-sealed-secret-key'.

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-gateway-secret
  namespace: api-gateway-local
spec:
  encryptedData:
    API_KEY: AQCZA+PJG4Q+yH5EB23kUw1q6JrmdKGC1Pj8+vpJqu0M5kk8LbStfWMa0L2smDAuvxFspkLsBQclfb9LFqVhSlmFDaAFiyxkgC7xXtOXuM0s4jILuSbi/LYvM4d7ZjKIyzHUPyzUCGfy26nf0PMg6Hqt46mlIRGlcozYqK7weXIaqwov2Q6G/pE6Hg+hFVf4VfUkx0H4+wfnsb/2AUqFkCliz//iXcxzv2v4P4QTHmuFuU/StmgNlPcmScyS1KpnfvFS5+Pbvgici5wss1e7cIHpeGv2QwOgBy2z9a8q0kmYIpobDPZgzkYnf0uV0S1TZxGdub320Tmz1goQm9wntPVgP9LDFKZDRvynyDSxo29pxX57GJzx1L/pK9czCMR1ltcVuKM/YULl11vV
  template:
    metadata:
      name: api-gateway-secret
      labels:
        app: api-gateway
    type: Opaque
